name: cib
version: "0.1"
license: "GPL-2.0-or-later"
date: 2026-01-27
description: |
    Cofinite Integral Braces in GAP

authors:
    - name: Rafał Lutowski
      url: mat.ug.edu.pl/~rlutowsk

maintainers:
    - name: Rafał Lutowski
      url: mat.ug.edu.pl/~rlutowsk

GAP: ">= 4.13"

www: https://rlutowsk.github.io/cib/
readme: README.md
packageinfo: https://rlutowsk.github.io/cib/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/rlutowsk/cib/releases/download/v0.1/cib-0.1.tar.gz

abstract: |

doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Lut26</span>]   <b class='BibAuthor'>Lutowski, R.</b>,
     <i class='BibTitle'>cib, Cofinite Integral Braces in GAP,
             Version 0.1</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://rlutowsk.github.io/cib/">https://rlutowsk.github.io/cib/</a></span>.
    </p>
    

bibtex: |
    @misc{ cib,
      author =           {Lutowski, R.},
      title =            {{cib}, {Cofinite Integral Braces in GAP}, {V}ersion 0.1},
      month =            {Jan},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href {https://rlutowsk.github.io/cib/} {\texttt{https://rlutowsk.github.io/}\discretionary {}{}{}\texttt{cib/}}},
      printedkey =       {Lut26}
    }

